# Generated by Django 5.2.6 on 2025-11-01

from django.db import migrations

def create_default_estados(apps, schema_editor):
    Estado = apps.get_model('rrhh', 'Estado')
    # Verificamos que no existan para evitar duplicados
    if not Estado.objects.filter(nombreestado='Postulado').exists():
        Estado.objects.create(
            nombreestado='Postulado',
            descripcion='Aspirante ha postulado',
            estado=True,
            idusuario=1  # cambiar si quieres otro usuario por defecto
        )
    if not Estado.objects.filter(nombreestado='Seleccionado para Entrevista').exists():
        Estado.objects.create(
            nombreestado='Seleccionado para Entrevista',
            descripcion='Aspirante seleccionado para entrevista',
            estado=True,
            idusuario=1
        )
    if not Estado.objects.filter(nombreestado='Rechazado').exists():
        Estado.objects.create(
            nombreestado='Rechazado',
            descripcion='Aspirante no continúa en el proceso',
            estado=True,
            idusuario=1
        )

class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0026_alter_estado_descripcion_alter_estado_idusuario_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_estados),
    ]
