# Generated by Django 5.2.6 on 2026-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0038_alter_authtoken_key_alter_authtoken_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='inicioLaboral',
            field=models.DateField(blank=True, db_column='inicioLaboral', null=True),
        ),
    ]
