# Generated by Django 5.2.6 on 2026-04-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0039_alter_empleado_iniciolaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='inicioLaboral',
            field=models.DateTimeField(blank=True, db_column='inicioLaboral', null=True),
        ),
    ]
