# Generated by Django 5.2.6 on 2026-04-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0040_alter_empleado_iniciolaboral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
