# Generated by Django 5.2.6 on 2026-04-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0041_alter_empleado_apellido_alter_empleado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
