# Generated by Django 5.2.6 on 2026-04-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0042_alter_convocatoria_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('idformulario', models.AutoField(db_column='idFormulario', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('idinduccion', models.ForeignKey(blank=True, db_column='idInduccion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.induccion')),
            ],
            options={
                'db_table': 'formulario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormularioRespuesta',
            fields=[
                ('idformulariorespuesta', models.AutoField(db_column='idFormularioRespuesta', primary_key=True, serialize=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('calificacion_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('idempleado', models.ForeignKey(blank=True, db_column='idEmpleado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.empleado')),
                ('idformulario', models.ForeignKey(db_column='idFormulario', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.formulario')),
                ('idusuario', models.ForeignKey(blank=True, db_column='idUsuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.usuario')),
            ],
            options={
                'db_table': 'formulario_respuesta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InduccionFormulario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaasignado', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('idformulario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.formulario')),
                ('idinduccion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.induccion')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('idpregunta', models.AutoField(db_column='idPregunta', primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('abierta', 'Abierta'), ('opcion_multiple', 'Opción múltiple')], max_length=20)),
                ('orden', models.IntegerField()),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('idformulario', models.ForeignKey(db_column='idFormulario', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.formulario')),
            ],
            options={
                'db_table': 'pregunta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('idopcion', models.AutoField(db_column='idOpcion', primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=300)),
                ('es_correcta', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('idpregunta', models.ForeignKey(db_column='idPregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.pregunta')),
            ],
            options={
                'db_table': 'opcion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('idrespuesta', models.AutoField(db_column='idRespuesta', primary_key=True, serialize=False)),
                ('respuesta_texto', models.TextField(blank=True, null=True)),
                ('puntaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('idformulariorespuesta', models.ForeignKey(db_column='idFormularioRespuesta', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.formulariorespuesta')),
                ('idopcion', models.ForeignKey(blank=True, db_column='idOpcion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.opcion')),
                ('idpregunta', models.ForeignKey(db_column='idPregunta', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.pregunta')),
            ],
            options={
                'db_table': 'respuesta',
                'managed': True,
            },
        ),
    ]
