# Generated by Django 5.2.6 on 2026-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0043_formulario_formulariorespuesta_induccionformulario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcion',
            name='orden',
            field=models.IntegerField(default=1),
        ),
    ]
