# Generated by Django 5.2.6 on 2026-04-25 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0045_FormularioComunede'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formulariorespuesta',
            unique_together={('idformulario', 'idempleado')},
        ),
    ]
