# Generated by Django 5.2.6 on 2026-05-01 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0046_alter_formulariorespuesta_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('iddimension', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dimension',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='iddimension',
            field=models.ForeignKey(blank=True, db_column='idDimension', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.dimension'),
        ),
    ]
