# Generated by Django 5.2.6 on 2026-05-01 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0047_dimension_pregunta_iddimension'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('idficha', models.AutoField(primary_key=True, serialize=False)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('idempleado', models.ForeignKey(db_column='idEmpleado', on_delete=django.db.models.deletion.CASCADE, related_name='fichas_medicas', to='rrhh.empleado')),
            ],
            options={
                'db_table': 'ficha_medica',
                'managed': True,
            },
        ),
    ]
