# Generated by Django 5.2.6 on 2026-05-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0048_fichamedica'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='formulariorespuesta',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='formulario',
            name='tipo',
            field=models.CharField(choices=[('induccion', 'Inducción'), ('medico', 'Médico')], default='induccion', max_length=20),
        ),
    ]
