# Generated by Django 5.2.6 on 2026-05-04 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0050_carga_encuesta_musculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('alergias', models.BooleanField(default=False)),
                ('alergias_detalle', models.TextField(blank=True)),
                ('operaciones', models.BooleanField(default=False)),
                ('operaciones_detalle', models.TextField(blank=True)),
                ('otras_enfermedades', models.BooleanField(default=False)),
                ('otras_detalle', models.TextField(blank=True)),
                ('idempleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EnfermedadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tiene', models.BooleanField(default=False)),
                ('tiempo', models.CharField(blank=True, max_length=50)),
                ('tratamiento', models.TextField(blank=True)),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.registroenfermedades')),
            ],
        ),
    ]
