# Generated by Django 5.2.6 on 2026-05-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0053_cargar_criterios_periodo_prueba_Acompanantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionGlobal',
            fields=[
                ('idevaluacionglobal', models.AutoField(db_column='idEvaluacionGlobal', primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('AUTO', 'Autoevaluación'), ('COORD', 'Coordinador')], max_length=20)),
                ('fortalezas', models.TextField(blank=True, null=True)),
                ('mejoras', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('idevaluacion', models.ForeignKey(db_column='idEvaluacion', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.evaluacion')),
            ],
            options={
                'db_table': 'evaluacion_global',
                'managed': True,
            },
        ),
    ]
