# Generated by Django 5.2.6 on 2026-05-06 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0054_evaluacionglobal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='observacion',
            field=models.CharField(db_column='observacion', max_length=250),
        ),
        migrations.AlterField(
            model_name='evaluacioncriterio',
            name='observacion',
            field=models.CharField(blank=True, db_column='observacion', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='historialpuesto',
            name='observacion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='observacion',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='terminacionlaboral',
            name='observacion',
            field=models.CharField(max_length=250),
        ),
    ]
