# Generated by Django 5.2.6 on 2026-05-08 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0056_cargar_criterios_periodo_prueba_Coordinadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InformeCapacitacion',
            fields=[
                ('idinformecapacitacion', models.AutoField(db_column='idInformeCapacitacion', primary_key=True, serialize=False)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('tematicas_contenidos', models.TextField(blank=True, null=True)),
                ('metodologia', models.TextField(blank=True, null=True)),
                ('conclusiones', models.TextField(blank=True, null=True)),
                ('aciertos_dificultades', models.TextField(blank=True, null=True)),
                ('utilidad_formacion', models.TextField(blank=True, null=True)),
                ('resultados_institucion', models.TextField(blank=True, null=True)),
                ('resultados_participante', models.TextField(blank=True, null=True)),
                ('compromiso_aplicacion', models.TextField(blank=True, null=True)),
                ('propuesta_seguimiento', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado_informe', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado'), ('REVISADO', 'Revisado')], default='PENDIENTE', max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('idusuario', models.IntegerField(db_column='idUsuario')),
                ('createdat', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updatedat', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('idempleadocapacitacion', models.ForeignKey(db_column='idEmpleadoCapacitacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='informes', to='rrhh.empleadocapacitacion')),
            ],
            options={
                'db_table': 'informecapacitacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InformeCapacitacionDocumento',
            fields=[
                ('idinformecapacitaciondocumento', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(auto_now=True)),
                ('iddocumento', models.ForeignKey(db_column='idDocumento', on_delete=django.db.models.deletion.DO_NOTHING, to='rrhh.documento')),
                ('idinformecapacitacion', models.ForeignKey(db_column='idInformeCapacitacion', on_delete=django.db.models.deletion.DO_NOTHING, related_name='documentos', to='rrhh.informecapacitacion')),
            ],
            options={
                'db_table': 'informecapacitaciondocumento',
                'managed': True,
            },
        ),
    ]
